version: '3.4'

services:
  bookstore.api:
    image: ${DOCKER_REGISTRY-}bookstoreapi
    build:
      context: .
      dockerfile: Bookstore.Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BookstoreDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: bookstore-sqlserver
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
